/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module letter_scan_patch(clk, frame_end_n, h4, h5, red, green, blue, green_new, blue_new);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [2:0] _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  input blue;
  wire blue;
  output blue_new;
  wire blue_new;
  input clk;
  wire clk;
  input frame_end_n;
  wire frame_end_n;
  input green;
  wire green;
  output green_new;
  wire green_new;
  input h4;
  wire h4;
  input h5;
  wire h5;
  wire [6:0] phase;
  input red;
  wire red;
  XNOR2 _29_ (
    .A(frame_end_n),
    .B(phase[0]),
    .Y(_00_[0])
  );
  INV_X1 _30_ (
    .A(frame_end_n),
    .Y(_04_)
  );
  AND2_X1 _31_ (
    .A(_04_),
    .B(phase[0]),
    .Y(_05_)
  );
  XOR2 _32_ (
    .A(phase[1]),
    .B(_05_),
    .Y(_00_[1])
  );
  NAND2 _33_ (
    .A(phase[1]),
    .B(_05_),
    .Y(_06_)
  );
  XNOR2 _34_ (
    .A(phase[2]),
    .B(_06_),
    .Y(_00_[2])
  );
  NAND4 _35_ (
    .A(_04_),
    .B(phase[1]),
    .C(phase[0]),
    .D(phase[2]),
    .Y(_07_)
  );
  XNOR2 _36_ (
    .A(phase[3]),
    .B(_07_),
    .Y(_00_[3])
  );
  INV_X1 _37_ (
    .A(phase[6]),
    .Y(_08_)
  );
  NAND2 _38_ (
    .A(_08_),
    .B(red),
    .Y(_09_)
  );
  XNOR2 _39_ (
    .A(phase[5]),
    .B(h5),
    .Y(_10_)
  );
  XNOR2 _40_ (
    .A(h4),
    .B(phase[4]),
    .Y(_11_)
  );
  NOR4 _41_ (
    .A(blue),
    .B(_09_),
    .C(_10_),
    .D(_11_),
    .Y(_12_)
  );
  OR2 _42_ (
    .A(green),
    .B(_12_),
    .Y(green_new)
  );
  OR2 _43_ (
    .A(blue),
    .B(_12_),
    .Y(blue_new)
  );
  AND2_X1 _44_ (
    .A(_08_),
    .B(_22_[0]),
    .Y(_13_)
  );
  INV_X1 _45_ (
    .A(phase[3]),
    .Y(_14_)
  );
  NOR2 _46_ (
    .A(_14_),
    .B(_07_),
    .Y(_15_)
  );
  MUX2 _47_ (
    .A(phase[4]),
    .B(_13_),
    .S(_15_),
    .Y(_01_)
  );
  INV_X1 _48_ (
    .A(phase[4]),
    .Y(_16_)
  );
  NOR3 _49_ (
    .A(_14_),
    .B(_16_),
    .C(_07_),
    .Y(_17_)
  );
  NOR2 _50_ (
    .A(phase[5]),
    .B(_17_),
    .Y(_18_)
  );
  AND2_X1 _51_ (
    .A(phase[5]),
    .B(_17_),
    .Y(_19_)
  );
  NOR3 _52_ (
    .A(_08_),
    .B(_14_),
    .C(_07_),
    .Y(_20_)
  );
  NOR3 _53_ (
    .A(_18_),
    .B(_19_),
    .C(_20_),
    .Y(_02_)
  );
  INV_X1 _54_ (
    .A(_15_),
    .Y(_21_)
  );
  MUX2 _55_ (
    .A(_21_),
    .B(_19_),
    .S(_08_),
    .Y(_03_)
  );
  DFF _56_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(phase[0]),
    .QB(_26_)
  );
  DFF _57_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(phase[1]),
    .QB(_27_)
  );
  DFF _58_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(phase[2]),
    .QB(_28_)
  );
  DFF _59_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(phase[3]),
    .QB(_25_)
  );
  DFF _60_ (
    .CK(clk),
    .D(_01_),
    .Q(phase[4]),
    .QB(_22_[0])
  );
  DFF _61_ (
    .CK(clk),
    .D(_02_),
    .Q(phase[5]),
    .QB(_24_)
  );
  DFF _62_ (
    .CK(clk),
    .D(_03_),
    .Q(phase[6]),
    .QB(_23_)
  );
  assign _22_[2:1] = phase[6:5];
endmodule
